name: Release

on:
  workflow_run:
    workflows:
      - CI
    branches: [main]
    types: 
      - completed
jobs:
  Release:
  if: ${{github.event.workflow_run.conclusion === 'success'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: pnpm i

      - name: semantic-release
        run: pnpm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
